<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
 
        <!-- Title Head -->
       	<title>Framework php</title>
 
        <!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
		
		<!-- Optional theme -->
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
		
		<!-- Latest compiled and minified JavaScript -->
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
		        
    </head>
    <body>
        <div class="container">
            <div class="header">
            	
                <ul class="nav nav-pills pull-right">
                    <li>
                    	<a href="#">Início</a>
                    </li>
                </ul>
                <h3 class="text-muted">PHP TDD</h3>
            </div>
             			
            <div>
            <hr>
                <?php $this->content() ?>
            </div>
 
            <div class="footer">
                <p class="muted credit pull-left">Company <a href="">© 2014</a></p>
                <p class="muted credit pull-right">Desenvolvido por <a href="#">AMZDev</a>.</p>
            </div>
        </div>
     
    </body>
</html>